version: '3'

services:
  api:
    image: dotz
    build:
      context: .
    ports:
      - "5100:80"
    networks:
      - api-network
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    hostname: mysql
    environment:
        - "MYSQL_DATABASE=mydb"
        - "MYSQL_USER=api-user"
        - "MYSQL_PASSWORD=api-password"
        - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "33060:3306"
    networks:
      - api-network
    
networks: 
    api-network:
        driver: bridge